# Generated by Django 3.1.4 on 2020-12-25 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_auto_20201225_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_player_1', models.CharField(default='', max_length=100)),
                ('team_player_2', models.CharField(default='', max_length=100)),
                ('team_player_3', models.CharField(default='', max_length=100)),
                ('team_player_4', models.CharField(default='', max_length=100)),
                ('team_player_5', models.CharField(default='', max_length=100)),
                ('team_player_6', models.CharField(default='', max_length=100)),
                ('team_player_7', models.CharField(default='', max_length=100)),
                ('team_player_8', models.CharField(default='', max_length=100)),
                ('team_player_9', models.CharField(default='', max_length=100)),
                ('team_player_10', models.CharField(default='', max_length=100)),
                ('Captain_name', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(default='', max_length=100)),
                ('Start_date', models.DateField(default='2020-12-12', max_length=100)),
                ('End_date', models.DateField(default='2020-12-12', max_length=100)),
                ('no_of_matches', models.DecimalField(decimal_places=3, default='1', max_digits=5, max_length=100)),
                ('no_of_teams', models.DecimalField(decimal_places=3, default='1', max_digits=5, max_length=15)),
                ('T_owner', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, related_name='teams', to='soccer.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default='2020-12-12', max_length=100)),
                ('Result', models.CharField(default='1', max_length=15)),
                ('Match_team1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='TeamOne', to='soccer.team')),
                ('Match_team2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='TeamTwo', to='soccer.team')),
                ('tournament', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='soccer.tournament')),
            ],
        ),
    ]
